/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HhButtonVariant } from "./types";
import { HhButtonSize } from "./components/button";
import { HhTableColumn } from "./showcase/data-table";
export { HhButtonVariant } from "./types";
export { HhButtonSize } from "./components/button";
export { HhTableColumn } from "./showcase/data-table";
export namespace Components {
    interface HhAccordion {
        /**
          * @default false
         */
        "multiple": boolean;
    }
    interface HhAccordionItem {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhAlert {
        /**
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default 'info'
         */
        "tone": 'info' | 'success' | 'warning' | 'danger';
    }
    interface HhBadge {
        /**
          * @default 'neutral'
         */
        "tone": 'neutral' | 'info' | 'success' | 'warning' | 'danger';
    }
    interface HhButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "focusControl": () => Promise<void>;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'medium'
         */
        "size": HhButtonSize;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": HhButtonVariant;
    }
    interface HhCard {
        /**
          * @default false
         */
        "interactive": boolean;
    }
    interface HhCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'on'
         */
        "value": string;
    }
    interface HhDataTable {
        /**
          * @default ''
         */
        "caption": string;
        /**
          * @default []
         */
        "columns": HhTableColumn[];
        /**
          * @default []
         */
        "rows": Record<string, string>[];
    }
    interface HhDialog {
        "close": () => Promise<void>;
        /**
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface HhDrawer {
        "close": () => Promise<void>;
        /**
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
        "show": () => Promise<void>;
        /**
          * @default 'right'
         */
        "side": 'left' | 'right';
    }
    interface HhEmptyState {
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default ''
         */
        "heading": string;
    }
    interface HhFormField {
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface HhIcon {
        "ariaLabel"?: string;
        "name": string;
    }
    interface HhIconButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "focusControl": () => Promise<void>;
        "label": string;
        /**
          * @default false
         */
        "loading": boolean;
        "name": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface HhInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        "focusControl": () => Promise<void>;
        /**
          * @default ''
         */
        "hint": string;
        "inputmode"?: HTMLInputElement['inputMode'];
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        "select": () => Promise<void>;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhMetricCard {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'neutral'
         */
        "tone": 'neutral' | 'positive' | 'negative';
        /**
          * @default ''
         */
        "trend": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhNav {
        /**
          * @default 'vertical'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    interface HhNavItem {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "href": string;
    }
    interface HhRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        "focusControl": () => Promise<void>;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhSpinner {
        /**
          * @default 'Loading'
         */
        "label": string;
    }
    interface HhStatus {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'neutral'
         */
        "tone": 'neutral' | 'success' | 'warning' | 'danger' | 'info';
    }
    interface HhSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
    }
    interface HhTab {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "value": string;
    }
    interface HhTabPanel {
        "value": string;
    }
    interface HhTabs {
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhTextarea {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        "focusControl": () => Promise<void>;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 4
         */
        "rows": number;
        /**
          * @default ''
         */
        "value": string;
    }
    interface HhToolbar {
    }
    interface HhTooltip {
        /**
          * @default 'top'
         */
        "placement": 'top' | 'bottom';
        /**
          * @default ''
         */
        "text": string;
    }
}
export interface HhAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhAccordionElement;
}
export interface HhAccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhAccordionItemElement;
}
export interface HhAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhAlertElement;
}
export interface HhButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhButtonElement;
}
export interface HhCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhCardElement;
}
export interface HhCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhCheckboxElement;
}
export interface HhDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhDialogElement;
}
export interface HhDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhDrawerElement;
}
export interface HhIconButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhIconButtonElement;
}
export interface HhInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhInputElement;
}
export interface HhNavItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhNavItemElement;
}
export interface HhRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhRadioElement;
}
export interface HhSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhSelectElement;
}
export interface HhSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhSwitchElement;
}
export interface HhTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhTabElement;
}
export interface HhTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhTabsElement;
}
export interface HhTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHhTextareaElement;
}
declare global {
    interface HTMLHhAccordionElementEventMap {
        "hhChange": string[];
    }
    interface HTMLHhAccordionElement extends Components.HhAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhAccordionElementEventMap>(type: K, listener: (this: HTMLHhAccordionElement, ev: HhAccordionCustomEvent<HTMLHhAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhAccordionElementEventMap>(type: K, listener: (this: HTMLHhAccordionElement, ev: HhAccordionCustomEvent<HTMLHhAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhAccordionElement: {
        prototype: HTMLHhAccordionElement;
        new (): HTMLHhAccordionElement;
    };
    interface HTMLHhAccordionItemElementEventMap {
        "hhToggle": boolean;
    }
    interface HTMLHhAccordionItemElement extends Components.HhAccordionItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhAccordionItemElementEventMap>(type: K, listener: (this: HTMLHhAccordionItemElement, ev: HhAccordionItemCustomEvent<HTMLHhAccordionItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhAccordionItemElementEventMap>(type: K, listener: (this: HTMLHhAccordionItemElement, ev: HhAccordionItemCustomEvent<HTMLHhAccordionItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhAccordionItemElement: {
        prototype: HTMLHhAccordionItemElement;
        new (): HTMLHhAccordionItemElement;
    };
    interface HTMLHhAlertElementEventMap {
        "hhDismiss": void;
    }
    interface HTMLHhAlertElement extends Components.HhAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhAlertElementEventMap>(type: K, listener: (this: HTMLHhAlertElement, ev: HhAlertCustomEvent<HTMLHhAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhAlertElementEventMap>(type: K, listener: (this: HTMLHhAlertElement, ev: HhAlertCustomEvent<HTMLHhAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhAlertElement: {
        prototype: HTMLHhAlertElement;
        new (): HTMLHhAlertElement;
    };
    interface HTMLHhBadgeElement extends Components.HhBadge, HTMLStencilElement {
    }
    var HTMLHhBadgeElement: {
        prototype: HTMLHhBadgeElement;
        new (): HTMLHhBadgeElement;
    };
    interface HTMLHhButtonElementEventMap {
        "hhPress": MouseEvent;
    }
    interface HTMLHhButtonElement extends Components.HhButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhButtonElementEventMap>(type: K, listener: (this: HTMLHhButtonElement, ev: HhButtonCustomEvent<HTMLHhButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhButtonElementEventMap>(type: K, listener: (this: HTMLHhButtonElement, ev: HhButtonCustomEvent<HTMLHhButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhButtonElement: {
        prototype: HTMLHhButtonElement;
        new (): HTMLHhButtonElement;
    };
    interface HTMLHhCardElementEventMap {
        "hhPress": MouseEvent | KeyboardEvent;
    }
    interface HTMLHhCardElement extends Components.HhCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhCardElementEventMap>(type: K, listener: (this: HTMLHhCardElement, ev: HhCardCustomEvent<HTMLHhCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhCardElementEventMap>(type: K, listener: (this: HTMLHhCardElement, ev: HhCardCustomEvent<HTMLHhCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhCardElement: {
        prototype: HTMLHhCardElement;
        new (): HTMLHhCardElement;
    };
    interface HTMLHhCheckboxElementEventMap {
        "hhChange": boolean;
    }
    interface HTMLHhCheckboxElement extends Components.HhCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhCheckboxElementEventMap>(type: K, listener: (this: HTMLHhCheckboxElement, ev: HhCheckboxCustomEvent<HTMLHhCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhCheckboxElementEventMap>(type: K, listener: (this: HTMLHhCheckboxElement, ev: HhCheckboxCustomEvent<HTMLHhCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhCheckboxElement: {
        prototype: HTMLHhCheckboxElement;
        new (): HTMLHhCheckboxElement;
    };
    interface HTMLHhDataTableElement extends Components.HhDataTable, HTMLStencilElement {
    }
    var HTMLHhDataTableElement: {
        prototype: HTMLHhDataTableElement;
        new (): HTMLHhDataTableElement;
    };
    interface HTMLHhDialogElementEventMap {
        "hhOpen": void;
        "hhClose": void;
    }
    interface HTMLHhDialogElement extends Components.HhDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhDialogElementEventMap>(type: K, listener: (this: HTMLHhDialogElement, ev: HhDialogCustomEvent<HTMLHhDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhDialogElementEventMap>(type: K, listener: (this: HTMLHhDialogElement, ev: HhDialogCustomEvent<HTMLHhDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhDialogElement: {
        prototype: HTMLHhDialogElement;
        new (): HTMLHhDialogElement;
    };
    interface HTMLHhDrawerElementEventMap {
        "hhOpen": void;
        "hhClose": void;
    }
    interface HTMLHhDrawerElement extends Components.HhDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhDrawerElementEventMap>(type: K, listener: (this: HTMLHhDrawerElement, ev: HhDrawerCustomEvent<HTMLHhDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhDrawerElementEventMap>(type: K, listener: (this: HTMLHhDrawerElement, ev: HhDrawerCustomEvent<HTMLHhDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhDrawerElement: {
        prototype: HTMLHhDrawerElement;
        new (): HTMLHhDrawerElement;
    };
    interface HTMLHhEmptyStateElement extends Components.HhEmptyState, HTMLStencilElement {
    }
    var HTMLHhEmptyStateElement: {
        prototype: HTMLHhEmptyStateElement;
        new (): HTMLHhEmptyStateElement;
    };
    interface HTMLHhFormFieldElement extends Components.HhFormField, HTMLStencilElement {
    }
    var HTMLHhFormFieldElement: {
        prototype: HTMLHhFormFieldElement;
        new (): HTMLHhFormFieldElement;
    };
    interface HTMLHhIconElement extends Components.HhIcon, HTMLStencilElement {
    }
    var HTMLHhIconElement: {
        prototype: HTMLHhIconElement;
        new (): HTMLHhIconElement;
    };
    interface HTMLHhIconButtonElementEventMap {
        "hhPress": MouseEvent;
    }
    interface HTMLHhIconButtonElement extends Components.HhIconButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhIconButtonElementEventMap>(type: K, listener: (this: HTMLHhIconButtonElement, ev: HhIconButtonCustomEvent<HTMLHhIconButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhIconButtonElementEventMap>(type: K, listener: (this: HTMLHhIconButtonElement, ev: HhIconButtonCustomEvent<HTMLHhIconButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhIconButtonElement: {
        prototype: HTMLHhIconButtonElement;
        new (): HTMLHhIconButtonElement;
    };
    interface HTMLHhInputElementEventMap {
        "hhInput": string;
        "hhChange": string;
    }
    interface HTMLHhInputElement extends Components.HhInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhInputElementEventMap>(type: K, listener: (this: HTMLHhInputElement, ev: HhInputCustomEvent<HTMLHhInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhInputElementEventMap>(type: K, listener: (this: HTMLHhInputElement, ev: HhInputCustomEvent<HTMLHhInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhInputElement: {
        prototype: HTMLHhInputElement;
        new (): HTMLHhInputElement;
    };
    interface HTMLHhMetricCardElement extends Components.HhMetricCard, HTMLStencilElement {
    }
    var HTMLHhMetricCardElement: {
        prototype: HTMLHhMetricCardElement;
        new (): HTMLHhMetricCardElement;
    };
    interface HTMLHhNavElement extends Components.HhNav, HTMLStencilElement {
    }
    var HTMLHhNavElement: {
        prototype: HTMLHhNavElement;
        new (): HTMLHhNavElement;
    };
    interface HTMLHhNavItemElementEventMap {
        "hhNavigate": string;
    }
    interface HTMLHhNavItemElement extends Components.HhNavItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhNavItemElementEventMap>(type: K, listener: (this: HTMLHhNavItemElement, ev: HhNavItemCustomEvent<HTMLHhNavItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhNavItemElementEventMap>(type: K, listener: (this: HTMLHhNavItemElement, ev: HhNavItemCustomEvent<HTMLHhNavItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhNavItemElement: {
        prototype: HTMLHhNavItemElement;
        new (): HTMLHhNavItemElement;
    };
    interface HTMLHhRadioElementEventMap {
        "hhChange": string;
    }
    interface HTMLHhRadioElement extends Components.HhRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhRadioElementEventMap>(type: K, listener: (this: HTMLHhRadioElement, ev: HhRadioCustomEvent<HTMLHhRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhRadioElementEventMap>(type: K, listener: (this: HTMLHhRadioElement, ev: HhRadioCustomEvent<HTMLHhRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhRadioElement: {
        prototype: HTMLHhRadioElement;
        new (): HTMLHhRadioElement;
    };
    interface HTMLHhSelectElementEventMap {
        "hhChange": string;
    }
    interface HTMLHhSelectElement extends Components.HhSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhSelectElementEventMap>(type: K, listener: (this: HTMLHhSelectElement, ev: HhSelectCustomEvent<HTMLHhSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhSelectElementEventMap>(type: K, listener: (this: HTMLHhSelectElement, ev: HhSelectCustomEvent<HTMLHhSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhSelectElement: {
        prototype: HTMLHhSelectElement;
        new (): HTMLHhSelectElement;
    };
    interface HTMLHhSpinnerElement extends Components.HhSpinner, HTMLStencilElement {
    }
    var HTMLHhSpinnerElement: {
        prototype: HTMLHhSpinnerElement;
        new (): HTMLHhSpinnerElement;
    };
    interface HTMLHhStatusElement extends Components.HhStatus, HTMLStencilElement {
    }
    var HTMLHhStatusElement: {
        prototype: HTMLHhStatusElement;
        new (): HTMLHhStatusElement;
    };
    interface HTMLHhSwitchElementEventMap {
        "hhChange": boolean;
    }
    interface HTMLHhSwitchElement extends Components.HhSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhSwitchElementEventMap>(type: K, listener: (this: HTMLHhSwitchElement, ev: HhSwitchCustomEvent<HTMLHhSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhSwitchElementEventMap>(type: K, listener: (this: HTMLHhSwitchElement, ev: HhSwitchCustomEvent<HTMLHhSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhSwitchElement: {
        prototype: HTMLHhSwitchElement;
        new (): HTMLHhSwitchElement;
    };
    interface HTMLHhTabElementEventMap {
        "hhPress": string;
    }
    interface HTMLHhTabElement extends Components.HhTab, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhTabElementEventMap>(type: K, listener: (this: HTMLHhTabElement, ev: HhTabCustomEvent<HTMLHhTabElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhTabElementEventMap>(type: K, listener: (this: HTMLHhTabElement, ev: HhTabCustomEvent<HTMLHhTabElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhTabElement: {
        prototype: HTMLHhTabElement;
        new (): HTMLHhTabElement;
    };
    interface HTMLHhTabPanelElement extends Components.HhTabPanel, HTMLStencilElement {
    }
    var HTMLHhTabPanelElement: {
        prototype: HTMLHhTabPanelElement;
        new (): HTMLHhTabPanelElement;
    };
    interface HTMLHhTabsElementEventMap {
        "hhChange": string;
    }
    interface HTMLHhTabsElement extends Components.HhTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhTabsElementEventMap>(type: K, listener: (this: HTMLHhTabsElement, ev: HhTabsCustomEvent<HTMLHhTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhTabsElementEventMap>(type: K, listener: (this: HTMLHhTabsElement, ev: HhTabsCustomEvent<HTMLHhTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhTabsElement: {
        prototype: HTMLHhTabsElement;
        new (): HTMLHhTabsElement;
    };
    interface HTMLHhTextareaElementEventMap {
        "hhInput": string;
        "hhChange": string;
    }
    interface HTMLHhTextareaElement extends Components.HhTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHhTextareaElementEventMap>(type: K, listener: (this: HTMLHhTextareaElement, ev: HhTextareaCustomEvent<HTMLHhTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHhTextareaElementEventMap>(type: K, listener: (this: HTMLHhTextareaElement, ev: HhTextareaCustomEvent<HTMLHhTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHhTextareaElement: {
        prototype: HTMLHhTextareaElement;
        new (): HTMLHhTextareaElement;
    };
    interface HTMLHhToolbarElement extends Components.HhToolbar, HTMLStencilElement {
    }
    var HTMLHhToolbarElement: {
        prototype: HTMLHhToolbarElement;
        new (): HTMLHhToolbarElement;
    };
    interface HTMLHhTooltipElement extends Components.HhTooltip, HTMLStencilElement {
    }
    var HTMLHhTooltipElement: {
        prototype: HTMLHhTooltipElement;
        new (): HTMLHhTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "hh-accordion": HTMLHhAccordionElement;
        "hh-accordion-item": HTMLHhAccordionItemElement;
        "hh-alert": HTMLHhAlertElement;
        "hh-badge": HTMLHhBadgeElement;
        "hh-button": HTMLHhButtonElement;
        "hh-card": HTMLHhCardElement;
        "hh-checkbox": HTMLHhCheckboxElement;
        "hh-data-table": HTMLHhDataTableElement;
        "hh-dialog": HTMLHhDialogElement;
        "hh-drawer": HTMLHhDrawerElement;
        "hh-empty-state": HTMLHhEmptyStateElement;
        "hh-form-field": HTMLHhFormFieldElement;
        "hh-icon": HTMLHhIconElement;
        "hh-icon-button": HTMLHhIconButtonElement;
        "hh-input": HTMLHhInputElement;
        "hh-metric-card": HTMLHhMetricCardElement;
        "hh-nav": HTMLHhNavElement;
        "hh-nav-item": HTMLHhNavItemElement;
        "hh-radio": HTMLHhRadioElement;
        "hh-select": HTMLHhSelectElement;
        "hh-spinner": HTMLHhSpinnerElement;
        "hh-status": HTMLHhStatusElement;
        "hh-switch": HTMLHhSwitchElement;
        "hh-tab": HTMLHhTabElement;
        "hh-tab-panel": HTMLHhTabPanelElement;
        "hh-tabs": HTMLHhTabsElement;
        "hh-textarea": HTMLHhTextareaElement;
        "hh-toolbar": HTMLHhToolbarElement;
        "hh-tooltip": HTMLHhTooltipElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface HhAccordion {
        /**
          * @default false
         */
        "multiple"?: boolean;
        "onHhChange"?: (event: HhAccordionCustomEvent<string[]>) => void;
    }
    interface HhAccordionItem {
        /**
          * @default ''
         */
        "label"?: string;
        "onHhToggle"?: (event: HhAccordionItemCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhAlert {
        /**
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        "onHhDismiss"?: (event: HhAlertCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "tone"?: 'info' | 'success' | 'warning' | 'danger';
    }
    interface HhBadge {
        /**
          * @default 'neutral'
         */
        "tone"?: 'neutral' | 'info' | 'success' | 'warning' | 'danger';
    }
    interface HhButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onHhPress"?: (event: HhButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'medium'
         */
        "size"?: HhButtonSize;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: HhButtonVariant;
    }
    interface HhCard {
        /**
          * @default false
         */
        "interactive"?: boolean;
        "onHhPress"?: (event: HhCardCustomEvent<MouseEvent | KeyboardEvent>) => void;
    }
    interface HhCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'on'
         */
        "value"?: string;
    }
    interface HhDataTable {
        /**
          * @default ''
         */
        "caption"?: string;
        /**
          * @default []
         */
        "columns"?: HhTableColumn[];
        /**
          * @default []
         */
        "rows"?: Record<string, string>[];
    }
    interface HhDialog {
        /**
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onHhClose"?: (event: HhDialogCustomEvent<void>) => void;
        "onHhOpen"?: (event: HhDialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface HhDrawer {
        /**
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onHhClose"?: (event: HhDrawerCustomEvent<void>) => void;
        "onHhOpen"?: (event: HhDrawerCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'right'
         */
        "side"?: 'left' | 'right';
    }
    interface HhEmptyState {
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default ''
         */
        "heading"?: string;
    }
    interface HhFormField {
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface HhIcon {
        "ariaLabel"?: string;
        "name": string;
    }
    interface HhIconButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label": string;
        /**
          * @default false
         */
        "loading"?: boolean;
        "name": string;
        "onHhPress"?: (event: HhIconButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface HhInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        "inputmode"?: HTMLInputElement['inputMode'];
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhInputCustomEvent<string>) => void;
        "onHhInput"?: (event: HhInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhMetricCard {
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "tone"?: 'neutral' | 'positive' | 'negative';
        /**
          * @default ''
         */
        "trend"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhNav {
        /**
          * @default 'vertical'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface HhNavItem {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "href"?: string;
        "onHhNavigate"?: (event: HhNavItemCustomEvent<string>) => void;
    }
    interface HhRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhRadioCustomEvent<string>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhSelectCustomEvent<string>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhSpinner {
        /**
          * @default 'Loading'
         */
        "label"?: string;
    }
    interface HhStatus {
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "tone"?: 'neutral' | 'success' | 'warning' | 'danger' | 'info';
    }
    interface HhSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhSwitchCustomEvent<boolean>) => void;
    }
    interface HhTab {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onHhPress"?: (event: HhTabCustomEvent<string>) => void;
        "value": string;
    }
    interface HhTabPanel {
        "value": string;
    }
    interface HhTabs {
        "onHhChange"?: (event: HhTabsCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhTextarea {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onHhChange"?: (event: HhTextareaCustomEvent<string>) => void;
        "onHhInput"?: (event: HhTextareaCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 4
         */
        "rows"?: number;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface HhToolbar {
    }
    interface HhTooltip {
        /**
          * @default 'top'
         */
        "placement"?: 'top' | 'bottom';
        /**
          * @default ''
         */
        "text"?: string;
    }

    interface HhAccordionAttributes {
        "multiple": boolean;
    }
    interface HhAccordionItemAttributes {
        "open": boolean;
        "value": string;
        "label": string;
    }
    interface HhAlertAttributes {
        "tone": 'info' | 'success' | 'warning' | 'danger';
        "heading": string;
        "dismissible": boolean;
    }
    interface HhBadgeAttributes {
        "tone": 'neutral' | 'info' | 'success' | 'warning' | 'danger';
    }
    interface HhButtonAttributes {
        "variant": HhButtonVariant;
        "size": HhButtonSize;
        "disabled": boolean;
        "loading": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
    }
    interface HhCardAttributes {
        "interactive": boolean;
    }
    interface HhCheckboxAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "name": string;
        "value": string;
        "required": boolean;
    }
    interface HhDataTableAttributes {
        "caption": string;
    }
    interface HhDialogAttributes {
        "open": boolean;
        "label": string;
        "closeOnEscape": boolean;
    }
    interface HhDrawerAttributes {
        "open": boolean;
        "label": string;
        "side": 'left' | 'right';
        "closeOnEscape": boolean;
    }
    interface HhEmptyStateAttributes {
        "heading": string;
        "description": string;
    }
    interface HhFormFieldAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "required": boolean;
    }
    interface HhIconAttributes {
        "name": string;
        "ariaLabel": string;
    }
    interface HhIconButtonAttributes {
        "name": string;
        "label": string;
        "size": 'small' | 'medium' | 'large';
        "disabled": boolean;
        "loading": boolean;
    }
    interface HhInputAttributes {
        "label": string;
        "name": string;
        "type": string;
        "value": string;
        "placeholder": string;
        "hint": string;
        "error": string;
        "required": boolean;
        "disabled": boolean;
        "readonly": boolean;
        "autocomplete": string;
        "inputmode": HTMLInputElement['inputMode'];
    }
    interface HhMetricCardAttributes {
        "label": string;
        "value": string;
        "trend": string;
        "tone": 'neutral' | 'positive' | 'negative';
    }
    interface HhNavAttributes {
        "orientation": 'horizontal' | 'vertical';
    }
    interface HhNavItemAttributes {
        "href": string;
        "active": boolean;
        "disabled": boolean;
    }
    interface HhRadioAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "name": string;
        "value": string;
        "required": boolean;
    }
    interface HhSelectAttributes {
        "label": string;
        "name": string;
        "value": string;
        "disabled": boolean;
        "required": boolean;
        "hint": string;
        "error": string;
    }
    interface HhSpinnerAttributes {
        "label": string;
    }
    interface HhStatusAttributes {
        "tone": 'neutral' | 'success' | 'warning' | 'danger' | 'info';
        "label": string;
    }
    interface HhSwitchAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "name": string;
    }
    interface HhTabAttributes {
        "value": string;
        "active": boolean;
        "disabled": boolean;
    }
    interface HhTabPanelAttributes {
        "value": string;
    }
    interface HhTabsAttributes {
        "value": string;
    }
    interface HhTextareaAttributes {
        "label": string;
        "name": string;
        "value": string;
        "placeholder": string;
        "hint": string;
        "error": string;
        "required": boolean;
        "disabled": boolean;
        "readonly": boolean;
        "rows": number;
    }
    interface HhTooltipAttributes {
        "text": string;
        "placement": 'top' | 'bottom';
    }

    interface IntrinsicElements {
        "hh-accordion": Omit<HhAccordion, keyof HhAccordionAttributes> & { [K in keyof HhAccordion & keyof HhAccordionAttributes]?: HhAccordion[K] } & { [K in keyof HhAccordion & keyof HhAccordionAttributes as `attr:${K}`]?: HhAccordionAttributes[K] } & { [K in keyof HhAccordion & keyof HhAccordionAttributes as `prop:${K}`]?: HhAccordion[K] };
        "hh-accordion-item": Omit<HhAccordionItem, keyof HhAccordionItemAttributes> & { [K in keyof HhAccordionItem & keyof HhAccordionItemAttributes]?: HhAccordionItem[K] } & { [K in keyof HhAccordionItem & keyof HhAccordionItemAttributes as `attr:${K}`]?: HhAccordionItemAttributes[K] } & { [K in keyof HhAccordionItem & keyof HhAccordionItemAttributes as `prop:${K}`]?: HhAccordionItem[K] };
        "hh-alert": Omit<HhAlert, keyof HhAlertAttributes> & { [K in keyof HhAlert & keyof HhAlertAttributes]?: HhAlert[K] } & { [K in keyof HhAlert & keyof HhAlertAttributes as `attr:${K}`]?: HhAlertAttributes[K] } & { [K in keyof HhAlert & keyof HhAlertAttributes as `prop:${K}`]?: HhAlert[K] };
        "hh-badge": Omit<HhBadge, keyof HhBadgeAttributes> & { [K in keyof HhBadge & keyof HhBadgeAttributes]?: HhBadge[K] } & { [K in keyof HhBadge & keyof HhBadgeAttributes as `attr:${K}`]?: HhBadgeAttributes[K] } & { [K in keyof HhBadge & keyof HhBadgeAttributes as `prop:${K}`]?: HhBadge[K] };
        "hh-button": Omit<HhButton, keyof HhButtonAttributes> & { [K in keyof HhButton & keyof HhButtonAttributes]?: HhButton[K] } & { [K in keyof HhButton & keyof HhButtonAttributes as `attr:${K}`]?: HhButtonAttributes[K] } & { [K in keyof HhButton & keyof HhButtonAttributes as `prop:${K}`]?: HhButton[K] };
        "hh-card": Omit<HhCard, keyof HhCardAttributes> & { [K in keyof HhCard & keyof HhCardAttributes]?: HhCard[K] } & { [K in keyof HhCard & keyof HhCardAttributes as `attr:${K}`]?: HhCardAttributes[K] } & { [K in keyof HhCard & keyof HhCardAttributes as `prop:${K}`]?: HhCard[K] };
        "hh-checkbox": Omit<HhCheckbox, keyof HhCheckboxAttributes> & { [K in keyof HhCheckbox & keyof HhCheckboxAttributes]?: HhCheckbox[K] } & { [K in keyof HhCheckbox & keyof HhCheckboxAttributes as `attr:${K}`]?: HhCheckboxAttributes[K] } & { [K in keyof HhCheckbox & keyof HhCheckboxAttributes as `prop:${K}`]?: HhCheckbox[K] };
        "hh-data-table": Omit<HhDataTable, keyof HhDataTableAttributes> & { [K in keyof HhDataTable & keyof HhDataTableAttributes]?: HhDataTable[K] } & { [K in keyof HhDataTable & keyof HhDataTableAttributes as `attr:${K}`]?: HhDataTableAttributes[K] } & { [K in keyof HhDataTable & keyof HhDataTableAttributes as `prop:${K}`]?: HhDataTable[K] };
        "hh-dialog": Omit<HhDialog, keyof HhDialogAttributes> & { [K in keyof HhDialog & keyof HhDialogAttributes]?: HhDialog[K] } & { [K in keyof HhDialog & keyof HhDialogAttributes as `attr:${K}`]?: HhDialogAttributes[K] } & { [K in keyof HhDialog & keyof HhDialogAttributes as `prop:${K}`]?: HhDialog[K] };
        "hh-drawer": Omit<HhDrawer, keyof HhDrawerAttributes> & { [K in keyof HhDrawer & keyof HhDrawerAttributes]?: HhDrawer[K] } & { [K in keyof HhDrawer & keyof HhDrawerAttributes as `attr:${K}`]?: HhDrawerAttributes[K] } & { [K in keyof HhDrawer & keyof HhDrawerAttributes as `prop:${K}`]?: HhDrawer[K] };
        "hh-empty-state": Omit<HhEmptyState, keyof HhEmptyStateAttributes> & { [K in keyof HhEmptyState & keyof HhEmptyStateAttributes]?: HhEmptyState[K] } & { [K in keyof HhEmptyState & keyof HhEmptyStateAttributes as `attr:${K}`]?: HhEmptyStateAttributes[K] } & { [K in keyof HhEmptyState & keyof HhEmptyStateAttributes as `prop:${K}`]?: HhEmptyState[K] };
        "hh-form-field": Omit<HhFormField, keyof HhFormFieldAttributes> & { [K in keyof HhFormField & keyof HhFormFieldAttributes]?: HhFormField[K] } & { [K in keyof HhFormField & keyof HhFormFieldAttributes as `attr:${K}`]?: HhFormFieldAttributes[K] } & { [K in keyof HhFormField & keyof HhFormFieldAttributes as `prop:${K}`]?: HhFormField[K] };
        "hh-icon": Omit<HhIcon, keyof HhIconAttributes> & { [K in keyof HhIcon & keyof HhIconAttributes]?: HhIcon[K] } & { [K in keyof HhIcon & keyof HhIconAttributes as `attr:${K}`]?: HhIconAttributes[K] } & { [K in keyof HhIcon & keyof HhIconAttributes as `prop:${K}`]?: HhIcon[K] } & OneOf<"name", HhIcon["name"], HhIconAttributes["name"]>;
        "hh-icon-button": Omit<HhIconButton, keyof HhIconButtonAttributes> & { [K in keyof HhIconButton & keyof HhIconButtonAttributes]?: HhIconButton[K] } & { [K in keyof HhIconButton & keyof HhIconButtonAttributes as `attr:${K}`]?: HhIconButtonAttributes[K] } & { [K in keyof HhIconButton & keyof HhIconButtonAttributes as `prop:${K}`]?: HhIconButton[K] } & OneOf<"name", HhIconButton["name"], HhIconButtonAttributes["name"]> & OneOf<"label", HhIconButton["label"], HhIconButtonAttributes["label"]>;
        "hh-input": Omit<HhInput, keyof HhInputAttributes> & { [K in keyof HhInput & keyof HhInputAttributes]?: HhInput[K] } & { [K in keyof HhInput & keyof HhInputAttributes as `attr:${K}`]?: HhInputAttributes[K] } & { [K in keyof HhInput & keyof HhInputAttributes as `prop:${K}`]?: HhInput[K] };
        "hh-metric-card": Omit<HhMetricCard, keyof HhMetricCardAttributes> & { [K in keyof HhMetricCard & keyof HhMetricCardAttributes]?: HhMetricCard[K] } & { [K in keyof HhMetricCard & keyof HhMetricCardAttributes as `attr:${K}`]?: HhMetricCardAttributes[K] } & { [K in keyof HhMetricCard & keyof HhMetricCardAttributes as `prop:${K}`]?: HhMetricCard[K] };
        "hh-nav": Omit<HhNav, keyof HhNavAttributes> & { [K in keyof HhNav & keyof HhNavAttributes]?: HhNav[K] } & { [K in keyof HhNav & keyof HhNavAttributes as `attr:${K}`]?: HhNavAttributes[K] } & { [K in keyof HhNav & keyof HhNavAttributes as `prop:${K}`]?: HhNav[K] };
        "hh-nav-item": Omit<HhNavItem, keyof HhNavItemAttributes> & { [K in keyof HhNavItem & keyof HhNavItemAttributes]?: HhNavItem[K] } & { [K in keyof HhNavItem & keyof HhNavItemAttributes as `attr:${K}`]?: HhNavItemAttributes[K] } & { [K in keyof HhNavItem & keyof HhNavItemAttributes as `prop:${K}`]?: HhNavItem[K] };
        "hh-radio": Omit<HhRadio, keyof HhRadioAttributes> & { [K in keyof HhRadio & keyof HhRadioAttributes]?: HhRadio[K] } & { [K in keyof HhRadio & keyof HhRadioAttributes as `attr:${K}`]?: HhRadioAttributes[K] } & { [K in keyof HhRadio & keyof HhRadioAttributes as `prop:${K}`]?: HhRadio[K] };
        "hh-select": Omit<HhSelect, keyof HhSelectAttributes> & { [K in keyof HhSelect & keyof HhSelectAttributes]?: HhSelect[K] } & { [K in keyof HhSelect & keyof HhSelectAttributes as `attr:${K}`]?: HhSelectAttributes[K] } & { [K in keyof HhSelect & keyof HhSelectAttributes as `prop:${K}`]?: HhSelect[K] };
        "hh-spinner": Omit<HhSpinner, keyof HhSpinnerAttributes> & { [K in keyof HhSpinner & keyof HhSpinnerAttributes]?: HhSpinner[K] } & { [K in keyof HhSpinner & keyof HhSpinnerAttributes as `attr:${K}`]?: HhSpinnerAttributes[K] } & { [K in keyof HhSpinner & keyof HhSpinnerAttributes as `prop:${K}`]?: HhSpinner[K] };
        "hh-status": Omit<HhStatus, keyof HhStatusAttributes> & { [K in keyof HhStatus & keyof HhStatusAttributes]?: HhStatus[K] } & { [K in keyof HhStatus & keyof HhStatusAttributes as `attr:${K}`]?: HhStatusAttributes[K] } & { [K in keyof HhStatus & keyof HhStatusAttributes as `prop:${K}`]?: HhStatus[K] };
        "hh-switch": Omit<HhSwitch, keyof HhSwitchAttributes> & { [K in keyof HhSwitch & keyof HhSwitchAttributes]?: HhSwitch[K] } & { [K in keyof HhSwitch & keyof HhSwitchAttributes as `attr:${K}`]?: HhSwitchAttributes[K] } & { [K in keyof HhSwitch & keyof HhSwitchAttributes as `prop:${K}`]?: HhSwitch[K] };
        "hh-tab": Omit<HhTab, keyof HhTabAttributes> & { [K in keyof HhTab & keyof HhTabAttributes]?: HhTab[K] } & { [K in keyof HhTab & keyof HhTabAttributes as `attr:${K}`]?: HhTabAttributes[K] } & { [K in keyof HhTab & keyof HhTabAttributes as `prop:${K}`]?: HhTab[K] } & OneOf<"value", HhTab["value"], HhTabAttributes["value"]>;
        "hh-tab-panel": Omit<HhTabPanel, keyof HhTabPanelAttributes> & { [K in keyof HhTabPanel & keyof HhTabPanelAttributes]?: HhTabPanel[K] } & { [K in keyof HhTabPanel & keyof HhTabPanelAttributes as `attr:${K}`]?: HhTabPanelAttributes[K] } & { [K in keyof HhTabPanel & keyof HhTabPanelAttributes as `prop:${K}`]?: HhTabPanel[K] } & OneOf<"value", HhTabPanel["value"], HhTabPanelAttributes["value"]>;
        "hh-tabs": Omit<HhTabs, keyof HhTabsAttributes> & { [K in keyof HhTabs & keyof HhTabsAttributes]?: HhTabs[K] } & { [K in keyof HhTabs & keyof HhTabsAttributes as `attr:${K}`]?: HhTabsAttributes[K] } & { [K in keyof HhTabs & keyof HhTabsAttributes as `prop:${K}`]?: HhTabs[K] };
        "hh-textarea": Omit<HhTextarea, keyof HhTextareaAttributes> & { [K in keyof HhTextarea & keyof HhTextareaAttributes]?: HhTextarea[K] } & { [K in keyof HhTextarea & keyof HhTextareaAttributes as `attr:${K}`]?: HhTextareaAttributes[K] } & { [K in keyof HhTextarea & keyof HhTextareaAttributes as `prop:${K}`]?: HhTextarea[K] };
        "hh-toolbar": HhToolbar;
        "hh-tooltip": Omit<HhTooltip, keyof HhTooltipAttributes> & { [K in keyof HhTooltip & keyof HhTooltipAttributes]?: HhTooltip[K] } & { [K in keyof HhTooltip & keyof HhTooltipAttributes as `attr:${K}`]?: HhTooltipAttributes[K] } & { [K in keyof HhTooltip & keyof HhTooltipAttributes as `prop:${K}`]?: HhTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hh-accordion": LocalJSX.IntrinsicElements["hh-accordion"] & JSXBase.HTMLAttributes<HTMLHhAccordionElement>;
            "hh-accordion-item": LocalJSX.IntrinsicElements["hh-accordion-item"] & JSXBase.HTMLAttributes<HTMLHhAccordionItemElement>;
            "hh-alert": LocalJSX.IntrinsicElements["hh-alert"] & JSXBase.HTMLAttributes<HTMLHhAlertElement>;
            "hh-badge": LocalJSX.IntrinsicElements["hh-badge"] & JSXBase.HTMLAttributes<HTMLHhBadgeElement>;
            "hh-button": LocalJSX.IntrinsicElements["hh-button"] & JSXBase.HTMLAttributes<HTMLHhButtonElement>;
            "hh-card": LocalJSX.IntrinsicElements["hh-card"] & JSXBase.HTMLAttributes<HTMLHhCardElement>;
            "hh-checkbox": LocalJSX.IntrinsicElements["hh-checkbox"] & JSXBase.HTMLAttributes<HTMLHhCheckboxElement>;
            "hh-data-table": LocalJSX.IntrinsicElements["hh-data-table"] & JSXBase.HTMLAttributes<HTMLHhDataTableElement>;
            "hh-dialog": LocalJSX.IntrinsicElements["hh-dialog"] & JSXBase.HTMLAttributes<HTMLHhDialogElement>;
            "hh-drawer": LocalJSX.IntrinsicElements["hh-drawer"] & JSXBase.HTMLAttributes<HTMLHhDrawerElement>;
            "hh-empty-state": LocalJSX.IntrinsicElements["hh-empty-state"] & JSXBase.HTMLAttributes<HTMLHhEmptyStateElement>;
            "hh-form-field": LocalJSX.IntrinsicElements["hh-form-field"] & JSXBase.HTMLAttributes<HTMLHhFormFieldElement>;
            "hh-icon": LocalJSX.IntrinsicElements["hh-icon"] & JSXBase.HTMLAttributes<HTMLHhIconElement>;
            "hh-icon-button": LocalJSX.IntrinsicElements["hh-icon-button"] & JSXBase.HTMLAttributes<HTMLHhIconButtonElement>;
            "hh-input": LocalJSX.IntrinsicElements["hh-input"] & JSXBase.HTMLAttributes<HTMLHhInputElement>;
            "hh-metric-card": LocalJSX.IntrinsicElements["hh-metric-card"] & JSXBase.HTMLAttributes<HTMLHhMetricCardElement>;
            "hh-nav": LocalJSX.IntrinsicElements["hh-nav"] & JSXBase.HTMLAttributes<HTMLHhNavElement>;
            "hh-nav-item": LocalJSX.IntrinsicElements["hh-nav-item"] & JSXBase.HTMLAttributes<HTMLHhNavItemElement>;
            "hh-radio": LocalJSX.IntrinsicElements["hh-radio"] & JSXBase.HTMLAttributes<HTMLHhRadioElement>;
            "hh-select": LocalJSX.IntrinsicElements["hh-select"] & JSXBase.HTMLAttributes<HTMLHhSelectElement>;
            "hh-spinner": LocalJSX.IntrinsicElements["hh-spinner"] & JSXBase.HTMLAttributes<HTMLHhSpinnerElement>;
            "hh-status": LocalJSX.IntrinsicElements["hh-status"] & JSXBase.HTMLAttributes<HTMLHhStatusElement>;
            "hh-switch": LocalJSX.IntrinsicElements["hh-switch"] & JSXBase.HTMLAttributes<HTMLHhSwitchElement>;
            "hh-tab": LocalJSX.IntrinsicElements["hh-tab"] & JSXBase.HTMLAttributes<HTMLHhTabElement>;
            "hh-tab-panel": LocalJSX.IntrinsicElements["hh-tab-panel"] & JSXBase.HTMLAttributes<HTMLHhTabPanelElement>;
            "hh-tabs": LocalJSX.IntrinsicElements["hh-tabs"] & JSXBase.HTMLAttributes<HTMLHhTabsElement>;
            "hh-textarea": LocalJSX.IntrinsicElements["hh-textarea"] & JSXBase.HTMLAttributes<HTMLHhTextareaElement>;
            "hh-toolbar": LocalJSX.IntrinsicElements["hh-toolbar"] & JSXBase.HTMLAttributes<HTMLHhToolbarElement>;
            "hh-tooltip": LocalJSX.IntrinsicElements["hh-tooltip"] & JSXBase.HTMLAttributes<HTMLHhTooltipElement>;
        }
    }
}
