/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HhStack {
        /**
          * @default 'stretch'
         */
        "align": 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 'column'
         */
        "direction": 'row' | 'column';
        /**
          * @default 'var(--hh-space-4)'
         */
        "gap": string;
    }
    interface HhSurface {
        /**
          * @default false
         */
        "elevated": boolean;
    }
}
declare global {
    interface HTMLHhStackElement extends Components.HhStack, HTMLStencilElement {
    }
    var HTMLHhStackElement: {
        prototype: HTMLHhStackElement;
        new (): HTMLHhStackElement;
    };
    interface HTMLHhSurfaceElement extends Components.HhSurface, HTMLStencilElement {
    }
    var HTMLHhSurfaceElement: {
        prototype: HTMLHhSurfaceElement;
        new (): HTMLHhSurfaceElement;
    };
    interface HTMLElementTagNameMap {
        "hh-stack": HTMLHhStackElement;
        "hh-surface": HTMLHhSurfaceElement;
    }
}
declare namespace LocalJSX {
    interface HhStack {
        /**
          * @default 'stretch'
         */
        "align"?: 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 'column'
         */
        "direction"?: 'row' | 'column';
        /**
          * @default 'var(--hh-space-4)'
         */
        "gap"?: string;
    }
    interface HhSurface {
        /**
          * @default false
         */
        "elevated"?: boolean;
    }

    interface HhStackAttributes {
        "direction": 'row' | 'column';
        "gap": string;
        "align": 'start' | 'center' | 'end' | 'stretch';
    }
    interface HhSurfaceAttributes {
        "elevated": boolean;
    }

    interface IntrinsicElements {
        "hh-stack": Omit<HhStack, keyof HhStackAttributes> & { [K in keyof HhStack & keyof HhStackAttributes]?: HhStack[K] } & { [K in keyof HhStack & keyof HhStackAttributes as `attr:${K}`]?: HhStackAttributes[K] } & { [K in keyof HhStack & keyof HhStackAttributes as `prop:${K}`]?: HhStack[K] };
        "hh-surface": Omit<HhSurface, keyof HhSurfaceAttributes> & { [K in keyof HhSurface & keyof HhSurfaceAttributes]?: HhSurface[K] } & { [K in keyof HhSurface & keyof HhSurfaceAttributes as `attr:${K}`]?: HhSurfaceAttributes[K] } & { [K in keyof HhSurface & keyof HhSurfaceAttributes as `prop:${K}`]?: HhSurface[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hh-stack": LocalJSX.IntrinsicElements["hh-stack"] & JSXBase.HTMLAttributes<HTMLHhStackElement>;
            "hh-surface": LocalJSX.IntrinsicElements["hh-surface"] & JSXBase.HTMLAttributes<HTMLHhSurfaceElement>;
        }
    }
}
