// Expresiones regulares para excepciones en español
export const SPANISH_EXCEPTIONS: Array<[RegExp, string]> = [
  [/([^fqgck]|\b)ui([ɾr])\b/g, "$1u_i$2"],
  [/([^fqgck]|\b)uid([oa]s?)\b/g, "$1u_id$2"],
  [/([^fqg]|\b)ui(mos|s)\b/g, "$1u_i$2"],
  [/([^fqg]|\b)u(i|iste|isteis)\b/g, "$1u_$2"],
  [/([^qg]|\b)ui([rɾ])(é|ás|á|emos|éis|an)\b/g, "$1u_i$2$3"],
  [/([^qg]|\b)ui([rɾ])í(a|as|amos|ais|an)\b/g, "$1u_i$2í$3"],
  [/([^gk])ua([ɾr])\b/g, "$1u_a$2"],
  [/([^gkc])uad([oa]s?)\b/g, "$1u_ad$2"],
  [/([^gkc]{2,})uand([oa]s?)\b/g, "$1u_and$2"],
  [/([^gkc]{2,})uant([ea]s?)\b/g, "$1u_ant$2"],
  [/([^gkc])uamos\b/g, "$1u_amos"],
  [/([^gkc])uáis\b/g, "$1u_áis"],
  [/([^gkc])uab(a|as|ais|an)\b/g, "$1u_ab$2"],
  [/([^gkc])uábamos\b/g, "$1u_ábamos"],
  [/([^gkc])u(é|aste|ó|asteis|aron|aɾon)\b/g, "$1u_$2"],
  [/([^gkc])ua([rɾ])(é|ás|á|emos|éis|an)\b/g, "$1u_a$2$3"],
  [/([^gkc])ua([rɾ])í(a|as|amos|ais|an)\b/g, "$1u_a$2í$3"],
];

// Onsets indivisibles en español
export const INDIVISIBLE_ONSETS = [
  "pl",
  "bl",
  "fl",
  "cl",
  "kl",
  "gl",
  "ll",
  "pr",
  "br",
  "fr",
  "cr",
  "kr",
  "gr",
  "rr",
  "dr",
  "tr",
  "ch",
  "dh",
  "rh",
  "th",
  "pr",
  "br",
  "fr",
  "cr",
  "gr",
  "dr",
  "tr",
];

// Codas indivisibles en español
export const INDIVISIBLE_CODAS = [
  "ns",
  "bs",
  "nz",
  "nd",
  "rt",
  "st",
  "ff",
  "ls",
  "lz",
  "zz",
  "ll",
  "nt",
  "rs",
  "mp",
  "rd",
];
